# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QAman < Formula
  desc "CLI tool for collecting text and image input"
  homepage "https://github.com/jyuniorcom/lead-qa"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jyuniorcom/lead-qa/releases/download/v1.0.0/lead-qa_darwin_amd64.tar.gz"
      sha256 "a5de16a4d802c3d5bd5d864620f13e40bfe94cdab065b8cd8cd988577864c203"

      define_method(:install) do
        bin.install "q-aman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jyuniorcom/lead-qa/releases/download/v1.0.0/lead-qa_darwin_arm64.tar.gz"
      sha256 "cdeeadbae86947caa7ea694dbf8fbc043958402c6706b908cff48ce448b9c93b"

      define_method(:install) do
        bin.install "q-aman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jyuniorcom/lead-qa/releases/download/v1.0.0/lead-qa_linux_amd64.tar.gz"
      sha256 "ecd936e1c0c66f56dac27c3c2206dd1b730e45fea15b01ce5a85312b35517142"
      define_method(:install) do
        bin.install "q-aman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jyuniorcom/lead-qa/releases/download/v1.0.0/lead-qa_linux_arm64.tar.gz"
      sha256 "b56c2d16264f1c4bc7de4f0e7372f528134c917f93002b32218a22af00fd4775"
      define_method(:install) do
        bin.install "q-aman"
      end
    end
  end

  test do
    system "#{bin}/q-aman", "--version"
  end
end
